### ISSUE TITLE
JWK Cache in Cache API instead of KV

### ISSUE THREAD

**Issue by nathanclevenger** [honojs/firebase-auth#10]
Great work here @Code-Hex!

As I was reviewing your code, I had one key question: why did you choose to cache the JWK token in KV instead of the Cache API?

In my experience, for this type of use case, the Cache API is actually quite a bit faster overall:
 - if the KV is not cached at the local CF Colo then it takes 100-200ms
 - once KV is cached, it usually takes 8-12ms
 - If the Cache API hits, it's usually 4-10ms, and if it's a miss, you can fetch from Google's endpoint in 20-40ms vs the 100-200ms that miss in KV takes
 - The KV requires additional configuration and setup with Bindings in wrangler.toml
 - Finally, KV has additional costs while the Cache API does not.

Let me know your thoughts, thanks!

**Comment by Code-Hex** [comment]
@nathanclevenger Hi 👋 
Thanks for your review! I really appreciate it!!

I can understand your opinion. I agree with using Cache API instead of KV.

However, My opinion is simple, I just couldn't think of what code to write using Cache API. If you have any ideas, let me know, I'd be very happy to help!

This is a reference for the Cache API: https://developers.cloudflare.com/workers/runtime-apis/cache/

Here is my understanding and description of what I am struggling with.

1. According to the reference, the key used for caching must be a Request object.
2. The fetched public key endpoint responds [Cache-Control as a header](https://github.com/Code-Hex/firebase-auth-cloudflare-workers/blob/a2d752f3320291c710afe0ebb5f3d67d79c10ff0/src/jwk-fetcher.ts#L48).
3. I want to keep a cache for the TTL of this header.

I don't know how to assemble the request object to use the Cache API at this time.

**Comment by nathanclevenger** [comment]
Yes, it's pretty simple: 

```
let res = await fetch(url, { cf: { cacheTtl: 24 * 60 * 60,  cacheEverything: true }})
```

<https://developers.cloudflare.com/workers/examples/cache-using-fetch/>

**Comment by Code-Hex** [comment]
Exactly! but it is not used 2. So I thought it is difficult.

> The fetched public key endpoint responds [Cache-Control as a header](https://github.com/Code-Hex/firebase-auth-cloudflare-workers/blob/a2d752f3320291c710afe0ebb5f3d67d79c10ff0/src/jwk-fetcher.ts#L48).

**Comment by Code-Hex** [comment]
I think this is also one big problem 😢 

> Only Workers deployed to custom domains have access to functional cache operations.

https://developers.cloudflare.com/workers/runtime-apis/cache/

**Comment by yusukebe** [comment]
How about using Durable Objects? This is sometimes used for session management.

**Comment by nathanclevenger** [comment]
> How about using Durable Objects? This is sometimes used for session management.

Durable Objects would be slower in this case ... we're working on an example that uses DOs to store the OAuth data though:
https://github.com/drivly/do-oauth-template

**Comment by nathanclevenger** [comment]
> Exactly! but it is not used 2. So I thought it is difficult.
> 
> > The fetched public key endpoint responds [Cache-Control as a header](https://github.com/Code-Hex/firebase-auth-cloudflare-workers/blob/a2d752f3320291c710afe0ebb5f3d67d79c10ff0/src/jwk-fetcher.ts#L48).

What is the actual response on the cache-control header of the public key?  If it is cacheable by default, then the fetch will do that automatically, although you're right, I forgot about it not caching on workers.dev subdomains ...

**Comment by Code-Hex** [comment]
This is an example fetched public-key response using curl

```
curl https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com -v
*   Trying 172.217.31.138:443...
* Connected to www.googleapis.com (172.217.31.138) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=upload.video.google.com
*  start date: Jul 11 08:24:09 2022 GMT
*  expire date: Oct  3 08:24:08 2022 GMT
*  subjectAltName: host "www.googleapis.com" matched cert's "*.googleapis.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com]
* h2h3 [:scheme: https]
* h2h3 [:authority: www.googleapis.com]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x13500aa00)
> GET /robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com HTTP/2
> Host: www.googleapis.com
> user-agent: curl/7.84.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< vary: X-Origin
< vary: Referer
< vary: Origin,Accept-Encoding
< server: scaffolding on HTTPServer2
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< date: Mon, 01 Aug 2022 14:29:30 GMT
< expires: Mon, 01 Aug 2022 21:05:05 GMT
< cache-control: public, max-age=23735, must-revalidate, no-transform
< content-type: application/json; charset=UTF-8
< age: 18
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< accept-ranges: none
<
{
  "keys": [
    {
      "kty": "RSA",
      "use": "sig",
      "kid": "1af60c17e2d6f8ad534c400c5a16d676fad777e6",
      "e": "AQAB",
      "alg": "RS256",
      "n": "tMLB6tGppieLNp6z50XKtjzB8ZqMMJaCe4Dh8XbluV8KxyhAXzBejpY904u3K-biwTRY9B5VlWVBR_VdTY0brQARYpngln60FABhwW96VfJYKLj1FgUl3jZk2W2pwpIbwD3-Dl6z4SHfUnugxCJFpkplRpf6jui7LdXXN2ojpauUnp7QgMAsNpJ6CqgBXICxs7zA4g0xkEUPVrbRhnsYybYm_svrOcmcOUF6sFh0TiSqTJOF8IDddmLmjurtE-kqUq0nXMyW0u9gDKNM97NVEhHeYQ7IIMVMACH0Bfika_DodgEW8ZsFYgeuDbNNzGqUIBsF1sXO9DKWO0AiEBg8Pw"
    },
    {
      "e": "AQAB",
      "n": "2Q54i1HTuYOPMC1UBLaOzWkpT6W2M7n28snXhh46mXAr8-jhauxziSb0iQidZQ7r9PUgmrX4Zm3ZuZ2aEqwIh1kz4jZcNIwzPY9DpqjHtnJf1kMe-zPTuUiZXERc4tiYHfSTiEE6VNOnPxzOF5aQep3fK0Sh1xGrUo92sNYd_zaIC9Zchrif63sWfElq7uCcqEJ67hqWkBVm1FVzusjZg9IGyxerjqdp2qzwtDzA2KxEB3eJMUWyUx5-FNSqN6f9fd5S-BZ6a2DhaLYtm5I6JFqpRu9D1190XXlPl8FM67Ru5tpXvlF0x_4VRdoJADL2N0MzUMFdB5zoNupnZKzjgQ",
      "kty": "RSA",
      "kid": "063a7ca43c3c7603674eda4be97725b73d0dc01f",
      "use": "sig",
      "alg": "RS256"
    }
  ]
}
```

The cache-control header is specified [`must-revalidate`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#:~:text=directive%20to%20use.-,must%2Drevalidate,-The%20must%2Drevalidate) directive. So I am a little hesitant to use parameters other than max-age specified in cache-control. 


```
cache-control: public, max-age=23735, must-revalidate, no-transform
```

**Comment by nathanclevenger** [comment]
yes @Code-Hex I'm using worker-auth-providers in the example I shared

I just ran some benchmarks, just getting the request from <https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com> is sub-100ms which is faster than KV cold anyway

if you create a variable in global scope, then you would only need to make the request the first time a worker is cold-started, and then it would be instant.

**Comment by Code-Hex** [comment]
This is just curious, How do you measure the performance? Is it using tools like apache bench?

Yes, in case you are wondering about this, I use [singletons](https://github.com/Code-Hex/firebase-auth-cloudflare-workers/tree/main#workerskvstoresinglegetorinitializecachekey-string-cfkvnamespace-kvnamespace-workerskvstoresingle) so initialization only needs to be done once.

> if you create a variable in global scope, then you would only need to make the request the first time a worker is cold-started, and then it would be instant.

**Comment by nathanclevenger** [comment]
ok perfect - I wrote a bunch of tools to benchmark things Cache, KV, DO, etc ... I haven't open-sourced it yet but here's where I'm measuring some things: <https://api.mt> ... I also put the GoogleJWKS on my worker [status page](https://apistatus.page) to start measuring latency from workers around the world

**Comment by nathanclevenger** [comment]
> I had never considered using Durable Object. It is a new idea but I don't have knowledge about it. I need to learn for Durable Object...

Using a DO to cache this would be much slower, because not all colo locations create them, and it's a hop from one worker to another, so you also have an additional small cold-start time for both workers here.

**Comment by chimame** [comment]
The Cache API is faster than KV, but has the biggest drawback that creating a cache does not always result in a cache hit.

https://developers.cloudflare.com/workers/runtime-apis/cache/#background

> The Cache API is available globally but the contents of the cache do not replicate outside of the originating data center. A GET /users response can be cached in the originating data center, but will not exist in another data center unless it has been explicitly created.

I believe that several Cloudflare Workers share a datacenter in Pop where they operate, but the Cache API cache is only stored in one datacenter. For example, I heard that there are currently 4 data centers in Japan. Even in the small country of Japan, there are four data centers, which means that depending on the region, the cache may or may not be hit, even if the cache is stored in the same data center. In such a situation, if we consider cache purging, we need to purge caches in multiple data centers.

So if you want to cache it completely.

- KV
- DO
- request cahce

I think one of them may need to be selected as a cache.

I hope this helps you in your choice of cache requirements.

**Comment by Code-Hex** [comment]
@chimame Thanks for your good help!

I didn't know that Cloudflare Workers cache API does not replicate to outside of the originating data center.

I see. If that is the case, I would like to adopt the interface as it is now, for once.

**Comment by Code-Hex** [comment]
If there are any problems, we will re-open it again.
