### ISSUE TITLE
Migrate to monorepo and `@hono/firebase-auth`

### ISSUE THREAD

**Issue by yusukebe** [honojs/firebase-auth#12]
Hi @Code-Hex !

We are going to do three things:

1. Manage this middleware under the [middleware monorepo](https://github.com/honojs/middleware). ref: [hono#601](https://github.com/honojs/hono/issues/601)
2. Publish this middleware as `@hono/firebase-auth`. ref: [hono#738](https://github.com/honojs/hono/issues/738)
3. Have Deno users use `npm:@hono/firebase-auth`.

So, can you let me do these things? I'll try to move the repository while keeping Git history. After the migration is complete, you can keep maintaining the project.

**Comment by Code-Hex** [comment]
@yusukebe Sure!
Thank you so much!

**Comment by yusukebe** [comment]
Hi @Code-Hex !

I've finished the migrations:

1. Moving to the monorepo.
2. Rename to `@hono/firebase-auth`.

Now, let's do the development on the following the monorepo:

https://github.com/honojs/middleware/tree/main/packages/firebase-auth

And I'll archive this repository later. Thanks!

**Comment by yusukebe** [comment]
Okay, I'll make this repo "private".
